
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Dec  3 2021 16:21:24 IST (Dec  3 2021 10:51:24 UTC)

// Verification Directory fv/jkff 

module jkff(reset, clk, j, k, q, qnot);
  input reset, clk, j, k;
  output q, qnot;
  wire reset, clk, j, k;
  wire q, qnot;
  wire n_0, n_2;
  DFFTRX1 q_reg(.CK (clk), .D (n_2), .RN (n_0), .Q (q), .QN (qnot));
  OAI2BB2XL g98__8780(.A0N (j), .A1N (qnot), .B0 (qnot), .B1 (k), .Y
       (n_2));
  INVXL g100(.A (reset), .Y (n_0));
endmodule

